### PR TITLE
Multiple images

### PR DESCRIPTION
**Pull request by lbaehren**
- Adjust directory structure and surrounding scripts to support multiple Docker images; images are organized by operating system and release version (similar to what we established for the Anaconda packages).
- Added Makefile to provide simple interface for building images and running them.
- Added license information as already the case for the Anaconda packages.

### CODE REVIEW

**Comment by cmarquardt** [comment]
Excellent. Thank you, Lars;-)

One question: How would we handle the versioning of MetTools images? Right now you are using the tag for the Linux base image, and have that version included if I understand correctly. I think we could leave the base distribution in the tag, but use the Mettools version number. E.g., something like `mettools:3.0-ubuntu` or `mettools:opensuse-3.0`.

**Comment by lbaehren** [comment]
Excellent question: Thinking about it it would opt for e.g. `mettools:3.0-ubuntu1604` because this also enables up to (if needed) provide a given MetTools version based on different distributions (e.g `mettools:3.0-ubuntu1804`).

**Comment by cmarquardt** [comment]
Nice;-)

**Comment by cmarquardt** [comment]
Nice;-) Thanks a lot...

**Pull request merged**
