### PR TITLE
Updates Dockerfile

### PR DESCRIPTION
**Pull request by lbaehren**
- Move installation of CMake to conda - version installed via package manager ran into conflict w.r.t. libcurl.
- Create SSH key for new user to subsequently allow access to Gitlab repositories.
- Add function to bash script to wrap build of Docker image.

### CODE REVIEW

**Comment by cmarquardt** [comment]
Why do we need an ssh key? I don't think this should be in a publicly available image.

**Comment by lbaehren** [comment]
Point well made. Remove SSH key generation and started README to collect usage information and open questions.

**Comment by lbaehren** [comment]
Tried to push directly to original repository after fixing commits, but no permissions.

**Comment by cmarquardt** [comment]
Na, I have to merge it...

**Pull request merged**
